[package]
name = "music-player"
version = "0.1.0"
authors = ["reujab <reujab@gmail.com>"]

[dependencies]
chan-signal = "0.3.1"
fmod = "0.9.24"
id3 = "0.2.3"
mp3-duration = "0.1.3"
mp3-metadata = "0.3.0"
rand = "0.4.2"
termion = "1.5.1"
walkdir = "2.1.4"
